[package]
name = "zettel-core"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[features]
default = []
git = []
search = []
templates = []
