# crates/zettel-cli/Cargo.toml
[package]
name = "zettel-cli"
description = "Command-line interface for Zettelkasten management"
readme = "README.md"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "zettel"
path = "src/main.rs"

[features]
default = ["full"]
full = ["search", "templates", "git", "completions"]
search = ["zettel-core/search"]
templates = ["zettel-core/templates"]
git = ["zettel-core/git"]
completions = ["clap_complete"]

[dependencies]
zettel-core = { path = "../zettel-core", features = ["search", "templates"] }
clap.workspace = true
clap_complete = { version = "4.0", optional = true }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
console.workspace = true
atty.workspace = true
indicatif.workspace = true

[dev-dependencies]
tempfile.workspace = true
assert_cmd = "2.0"
predicates = "3.0"
